apiVersion: v1
kind: Service
metadata:
  name: {{ app_name }}-service
spec:
  type: LoadBalancer
  ports:
    - port: 80  # The port that the service will expose externally
      targetPort: {{ container_port }}  # Port inside the container
  selector:
    app: {{ app_name }}
